---
- name: setup mysql with accounts db and remote login
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: update apt repository
      apt:
        update_cache: yes
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
    - name: installing python2
      apt:
        name: python2-pip
        state: present

    - name: Install Python 3
      apt:
        name: python3-pip
        state: present
    - name: Install MySQL client for Python 3.x
      pip:
        name: PyMySQL
        state: present
        executable: pip3
    - name: Download get-pip.py for Python 2.x
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip for Python 2.x
      command: python2 /tmp/get-pip.py

    - name: Install MySQL client for Python 2.x
      pip:
       name: mysqlclient
       state: present
       executable: pip2
    - name: creating mysql user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present
    - name: creating acounts db
      mysql_db:
        name: "{{dbname}}"
        state: present
    - name: Enable remote login to mysql svc
      lineinfile:
        path: /etc/mysql/msql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql
      tags:
        - conf
  handlers:
   - name: Restart mysql
     service:
      name: mysql
      state: restarted