---
- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  gather_facts: no
  tasks:
    - name: Install Erlang Repository Package
      command: apt-get -y install socat logrotate init-system-helpers adduser
    - name: wget
      command: apt-get -y install wget
    - name: wget
      command: cd /opt
    - name: download package
      command: wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v4.0.3/rabbitmq-server_4.0.3-1_all.deb




    - name: Install Rabbit MQ
      command: dpkg -i rabbitmq-server_4.0.3-1_all.deb



    - name: Start & Enable RMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc

    - name: Config setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ
      tags:
        - conf


    - rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf


    - name: Enables the rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted