---
- name: Install RabbitMQ on Ubuntu 22.04
  hosts: rmqsrvgrp
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present

    - name: Add RabbitMQ signing key
      apt_key:
        url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-release.gpg
        state: present

   - name: Add RabbitMQ repository
     apt_repository:
        repo: 'deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu jammy main'
        state: present

    - name: Update apt repository again
      apt:
       update_cache: yes

    - name: Install RabbitMQ server
      apt:
        name: rabbitmq-server
        state: present


    - name: Start & Enable RMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc

    - name: Config setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ
      tags:
        - conf


    - rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf


    - name: Enables the rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted